# values.yaml

## ================================
## Prometheus 설정
## ================================
prometheus:
  prometheusSpec:
    # 데이터 보존 기간 설정 (기본값: 30d)
    retention: 20d
    # Prometheus 레플리카 수 설정
    replicas: 1
    # 모든 ServiceMonitor/PodMonitor 수집
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

## ================================
## Alertmanager 설정
## ================================
alertmanager:
  alertmanagerSpec:
    replicas: 2

## ================================
## Grafana 기본 설정
## ================================
grafana:
  enabled: true
  adminPassword: admin123!
  service:
    type: NodePort
    nodePort: 30007
  # 기본 대시보드 자동 설정 (Prometheus + Node + k8s 리소스 포함)
  defaultDashboardsEnabled: true
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true