# values.yaml

## ================================
## Prometheus 설정
## ================================
prometheus:
  prometheusSpec:
    # 데이터 보존 기간 설정 (기본값: 30d)
    retention: 15d
    # 모든 메트릭 수집집
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

## ================================
## Kubelet 메트릭 설정 (기본 활성화됨)
## ================================
kubelet:
  enabled: true
  serviceMonitor:
    enabled: true
    # cAdvisor, probes 등은 기본으로 활성화됨

## ================================
## Alertmanager 설정
## ================================
alertmanager:
  alertmanagerSpec:

## ================================
## kube-state-metrics 설정
## ================================
kubeStateMetrics:
  enabled: true

## ================================
## node-exporter 설정 (GitOps 테스트: 활성화)
## ================================
nodeExporter:
  enabled: true

## ================================
## Grafana 기본 설정
## ================================
grafana:
  enabled: true
  # Grafana 레플리카 설정 (CI/CD 테스트)
  replicaCount: 3
  adminPassword: admin
  service:
    type: NodePort
    nodePort: 30006
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  # 기본 대시보드 자동 설정 (Prometheus + Node + k8s 리소스 포함)
  defaultDashboardsEnabled: true
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true
