# values.yaml

## ================================
## Prometheus 설정
## ================================
prometheus:
  prometheusSpec:
    # 데이터 보존 기간 설정 (기본값: 30d)
    retention: 15d
    # Prometheus 레플리카 수 설정
    replicas: 2
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    # Kubelet 관련 지표 수집
    scrapeConfig:
      - job_name: 'kubelet'
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
        metric_relabel_configs:
          - source_labels: [__name__]
            regex: 'kubelet_runtime_operations_duration_seconds.*'
            action: keep
        metrics_path: /metrics
      - job_name: 'kubelet/cadvisor'
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
        metrics_path: /metrics/cadvisor
      - job_name: 'kubelet/resource'
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
        metrics_path: /metrics/resource

## ================================
## Alertmanager 설정
## ================================
alertmanager:
  alertmanagerSpec:
    # Alertmanager 레플리카 수 설정
    replicas: 2

## ================================
## kube-state-metrics 설정
## ================================
kubeStateMetrics:
  enabled: true

## ================================
## node-exporter 설정
## ================================
nodeExporter:
  enabled: true

## ================================
## Grafana 기본 설정
## ================================
grafana:
  enabled: true
  # Grafana 레플리카 설정 (CI/CD 테스트)
  replicaCount: 3
  adminPassword: newpassword123!
  service:
    type: NodePort
    nodePort: 30003
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  # 기본 대시보드 자동 설정 (Prometheus + Node + k8s 리소스 포함)
  defaultDashboardsEnabled: true
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true
