apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: msa-demo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/chan-hi/prometheus-gitops.git
    path: msa-demo
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: msa-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/template/metadata/annotations