apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-operator
    targetRevision: 0.91.1
    helm:
      values: |
        replicaCount: 1
        
        manager:
          env:
            ENABLE_WEBHOOKS: "true"
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
        
        admissionWebhooks:
          create: true
          certManager:
            enabled: false
          autoGenerateCert:
            enabled: true
            recreate: true
            certPeriodDays: 365
        
        crds:
          create: true
  destination:
    server: https://kubernetes.default.svc
    namespace: opentelemetry-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
