apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/lch-howger/prometheus-gitops.git
    path: otel-stack
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: opentelemetry-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/template/metadata/annotations
