name: Sync Argo CD

on:
  push:
    branches:
      - main
    paths:
      - 'values/**'
      - 'argo-app.yaml'

jobs:
  sync-argocd:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Argo CD Application
        run: |
          curl -k -X POST https://localhost:8080/api/v1/applications/prometheus-stack/sync \
            -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}"
