name: Sync Argo CD

on:
  push:
    branches:
      - main
    paths:
      - 'values/**'
      - 'argo-app.yaml'
      - 'logging-app.yaml'
      - 'prometheus-crds.yaml'
      - 'msa-demo-app.yaml'
      - 'msa-demo/**'

jobs:
  sync-argocd:
    runs-on: self-hosted
    steps:
      - name: Sync Prometheus CRDs
        run: |
          curl -k -X POST https://192.168.49.2:30169/api/v1/applications/prometheus-crds/sync \
            -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{}'
      
      - name: Sync Monitoring Stack
        run: |
          curl -k -X POST https://192.168.49.2:30169/api/v1/applications/prometheus-stack/sync \
            -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{}'
      
      - name: Sync Logging Stack
        run: |
          curl -k -X POST https://192.168.49.2:30169/api/v1/applications/logging-stack/sync \
            -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{}'
      
      - name: Sync MSA Demo
        run: |
          curl -k -X POST https://192.168.49.2:30169/api/v1/applications/msa-demo/sync \
            -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{}'
