name: Sync Argo CD

on:
  push:
    branches:
      - main
    paths:
      - 'monitoring/**'
      - 'logging/**'

jobs:
  sync-argocd:
    runs-on: self-hosted
    steps:
      - name: Sync Monitoring Stack
        run: |
          curl -k -X POST https://192.168.49.2:30169/api/v1/applications/prometheus-stack/sync \
            -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{}'
      
      - name: Sync Fluent Bit
        run: |
          curl -k -X POST https://192.168.49.2:30169/api/v1/applications/fluent-bit/sync \
            -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{}'
      
      - name: Sync Elasticsearch
        run: |
          curl -k -X POST https://192.168.49.2:30169/api/v1/applications/elasticsearch/sync \
            -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{}'
      
      - name: Sync Kibana
        run: |
          curl -k -X POST https://192.168.49.2:30169/api/v1/applications/kibana/sync \
            -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{}'
